In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import sqlite3

In [4]:
##connevtion with DB
conn = sqlite3.connect('customer_churn.db')
sql_query="""
 SELECT name FROM sqlite_master WHERE type='table';
"""
tables= pd.read_sql(sql_query,conn)
##Create dataDrame for each Table
for table_name in tables['name']:
    df=pd.read_sql(f"Select * from {table_name}", conn)
    globals()[f"df_{table_name}"]=df
    print(f"created df:df_{table_name}")
conn.close()

created df:df_db_customer
created df:df_db_subscription
created df:df_db_support

In [19]:
df_db_customer.columns

Index(['customerid', 'Customer_name', 'country', 'state', 'gender', 'dob'], dtype='str')

In [6]:
df_db_subscription.columns

Index(['customerid', 'subscription_start_date', 'subscription_type',
       'renewal_date', 'plan_type', 'contract_type', 'cancellation_date',
       'cancellation_reason', 'monthly_charges', 'cltv', 'churn_score'],
      dtype='str')

In [7]:
df_db_support.columns

Index(['customerid', 'complaint_date', 'escalations', 'csat_score', 'col_1',
       'comment'],
      dtype='str')

Cleaning of Customer Table

In [8]:
df_db_customer.head()

,customerid,name,country,state,gender,dob,interests,pincode
0,0002-ORFBO,keshav,India,Maharashtra,Male,1982-04-12 00:00:00,travel,None
1,0003-MKNFE,raghav,India,Karnataka,Male,1995-11-23 00:00:00,NaN,None
2,0004-TLHLJ,lalita,India,Delhi,Female,1978-02-15 00:00:00,movie,None
3,0011-IGKFF,mohan,India,Nagaland,Male,2001-08-30 00:00:00,NaN,None
4,0013-EXCHZ,mira,India,Delhi,Female,1990-05-05 00:00:00,drama,None

In [9]:
##Data Cleaning

In [10]:
df_db_customer.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   customerid  21 non-null     str
 1   name        21 non-null     str
 2   country     18 non-null     str
 3   state       21 non-null     str
 4   gender      21 non-null     str
 5   dob         21 non-null     str
 6   interests   4 non-null      str
 7   pincode     0 non-null      object
dtypes: object(1), str(7)
memory usage: 1.4+ KB

In [11]:
df_db_customer.rename(columns={'name':'Customer_name'},inplace=True)

In [12]:
##Drop columns
##df_db_customer.drop(df_db_customer.columns[-2:],axis=1,)
df_db_customer.drop(columns=['interests','pincode'],inplace=True)

In [13]:
df_db_customer.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerid     21 non-null     str
 1   Customer_name  21 non-null     str
 2   country        18 non-null     str
 3   state          21 non-null     str
 4   gender         21 non-null     str
 5   dob            21 non-null     str
dtypes: str(6)
memory usage: 1.1 KB

In [14]:
## Change the dob columns datatype to DateTime
df_db_customer['dob']=pd.to_datetime(df_db_customer['dob'])

In [15]:
##Replace the gender column
df_db_customer['gender']=df_db_customer['gender'].replace({'Men':'Male','Women':'Female'})

In [16]:
df_db_customer

    customerid Customer_name country          state  gender        dob
0   0002-ORFBO        keshav   India    Maharashtra    Male 1982-04-12
1   0003-MKNFE        raghav   India      Karnataka    Male 1995-11-23
2   0004-TLHLJ        lalita   India          Delhi  Female 1978-02-15
3   0011-IGKFF         mohan   India       Nagaland    Male 2001-08-30
4   0013-EXCHZ          mira   India          Delhi  Female 1990-05-05
5   0013-MHZWF         durga     NaN          Delhi  Female 1988-12-10
6   0013-SMEOE          mina   India      Meghalaya  Female 1976-09-21
7   0014-BMAQU         madan   India      Rajasthan    Male 1999-03-14
8   0015-UOCOJ          maya     NaN      Kathmandu  Female 1985-07-07
9   0016-QLJIS         arjun   Nepal      Kathmandu    Male 1993-10-29
10  0017-DINOC         shiva   India    Maharashtra    Male 1997-01-22
11  0017-IUDMW     rangadevi   India      Karnataka  Female 1981-06-18
12  0018-NYROU        chitra     NaN      Telangana  Female 2004-12-01
13  0019-EFAEP          raju   India      Meghalaya  Female 1992-04-25
14  0019-GFNTW        Madhav   India  Uttar Pradesh    Male 1979-11-11
15  0020-INWCK       parvati   India          Delhi  Female 1986-02-28
16  0020-JDNXP         rikim   India      Meghalaya  Female 1994-08-19
17  0021-IKXGC      vishakha   India      Rajasthan  Female 2000-09-02
18  0022-TCJCI    raghvendra   India      Telangana    Male 1983-12-30
19  0023-HGHWL       rishabh   India  Uttar Pradesh    Male 1991-05-14
20  0023-UYUPN        sudevi   India    Maharashtra  Female 1977-10-06

In [21]:
## Fix missing values-countries
df_db_customer[df_db_customer['country'].isnull()]

    customerid Customer_name country      state  gender        dob
5   0013-MHZWF         durga     NaN      Delhi  Female 1988-12-10
8   0015-UOCOJ          maya     NaN  Kathmandu  Female 1985-07-07
12  0018-NYROU        chitra     NaN  Telangana  Female 2004-12-01

In [52]:
## df = df_db_customer.dropna(subset=['country']) --create a table without null value
## df = df.set_index('state')['country'].to_dict() --set the state as index and select the country and make it dictionary

state_country_mapping=df_db_customer.dropna(subset=['country']).set_index('state')['country'].to_dict()
state_country_mapping

{'Maharashtra': 'India',
 'Karnataka': 'India',
 'Delhi': 'India',
 'Nagaland': 'India',
 'Meghalaya': 'India',
 'Rajasthan': 'India',
 'Kathmandu': 'Nepal',
 'Telangana': 'India',
 'Uttar Pradesh': 'India'}

In [48]:
## its mapping all the values of state column and place the matching value 
df_db_customer['country']=df_db_customer['country'].fillna(df_db_customer['state'].map(state_country_mapping))

In [49]:
df_db_customer

    customerid Customer_name country          state  gender        dob
0   0002-ORFBO        keshav   India    Maharashtra    Male 1982-04-12
1   0003-MKNFE        raghav   India      Karnataka    Male 1995-11-23
2   0004-TLHLJ        lalita   India          Delhi  Female 1978-02-15
3   0011-IGKFF         mohan   India       Nagaland    Male 2001-08-30
4   0013-EXCHZ          mira   India          Delhi  Female 1990-05-05
5   0013-MHZWF         durga   India          Delhi  Female 1988-12-10
6   0013-SMEOE          mina   India      Meghalaya  Female 1976-09-21
7   0014-BMAQU         madan   India      Rajasthan    Male 1999-03-14
8   0015-UOCOJ          maya   Nepal      Kathmandu  Female 1985-07-07
9   0016-QLJIS         arjun   Nepal      Kathmandu    Male 1993-10-29
10  0017-DINOC         shiva   India    Maharashtra    Male 1997-01-22
11  0017-IUDMW     rangadevi   India      Karnataka  Female 1981-06-18
12  0018-NYROU        chitra   India      Telangana  Female 2004-12-01
13  0019-EFAEP          raju   India      Meghalaya  Female 1992-04-25
14  0019-GFNTW        Madhav   India  Uttar Pradesh    Male 1979-11-11
15  0020-INWCK       parvati   India          Delhi  Female 1986-02-28
16  0020-JDNXP         rikim   India      Meghalaya  Female 1994-08-19
17  0021-IKXGC      vishakha   India      Rajasthan  Female 2000-09-02
18  0022-TCJCI    raghvendra   India      Telangana    Male 1983-12-30
19  0023-HGHWL       rishabh   India  Uttar Pradesh    Male 1991-05-14
20  0023-UYUPN        sudevi   India    Maharashtra  Female 1977-10-06

---Customer Table cleaning Done

Cleaning of subscription table

In [53]:
df_db_subscription.columns

Index(['customerid', 'subscription_start_date', 'subscription_type',
       'renewal_date', 'plan_type', 'contract_type', 'cancellation_date',
       'cancellation_reason', 'monthly_charges', 'cltv', 'churn_score'],
      dtype='str')

In [54]:
df_db_subscription.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customerid               21 non-null     str
 1   subscription_start_date  21 non-null     str
 2   subscription_type        21 non-null     str
 3   renewal_date             21 non-null     str
 4   plan_type                21 non-null     str
 5   contract_type            21 non-null     str
 6   cancellation_date        6 non-null      str
 7   cancellation_reason      6 non-null      str
 8   monthly_charges          21 non-null     float64
 9   cltv                     21 non-null     int64
 10  churn_score              21 non-null     int64
dtypes: float64(1), int64(2), str(8)
memory usage: 1.9 KB

In [55]:
df_db_subscription.head()

,customerid,subscription_start_date,subscription_type,renewal_date,plan_type,contract_type,cancellation_date,cancellation_reason,monthly_charges,cltv,churn_score
0,0002-ORFBO,2021-03-15,Refferal,2025-03-15,Standard,Annual,NaN,NaN,13.99,627,12
1,0003-MKNFE,2020-08-01,Paid,2024-08-01,Premium,Annual,2024-09-10,Switched to competitor,12.99,1150,91
2,0004-TLHLJ,2022-11-20,Organic,2025-11-20,Basic,Monthly,NaN,NaN,6.99,210,34
3,0011-IGKFF,2019-05-10,Paid,2025-05-10,Premium,Annual,NaN,NaN,22.99,1725,8
4,0013-EXCHZ,2023-01-05,Refferal,2024-01-05,Standard,Monthly,2024-02-28,Too expensive,13.99,195,88